export const SIZE_OPTIONS = ['sm', 'md', 'lg', 'xl'] as const;
export const COLOR_OPTIONS = [
    'primary',
    'secondary',
    'success',
    'warning',
    'danger',
    'contrast',
] as const;
export const SHAPE_OPTIONS = ['fill', 'outline', 'invisible'] as const;

export const TYPOGRAPHY = {
    sm: 'subtitle1',
    md: 'subtitle1',
    lg: 'subtitle1',
    xl: 'heading6',
} as const;

export const PHRASING_CONTENT = [
    'a',
    'abbr',
    'area',
    'b',
    'bdi',
    'bdo',
    'br',
    'button',
    'canvas',
    'cite',
    'code',
    'data',
    'datalist',
    'del',
    'dfn',
    'em',
    'embed',
    'i',
    'iframe',
    'img',
    'input',
    'ins',
    'kbd',
    'label',
    'link',
    'map',
    'mark',
    'math',
    'meta',
    'meter',
    'noscript',
    'object',
    'output',
    'progress',
    'q',
    'ruby',
    's',
    'samp',
    'script',
    'select',
    'small',
    'span',
    'strong',
    'sub',
    'sup',
    'svg',
    'template',
    'textarea',
    'time',
    'u',
    'var',
    'wbr',
] as const;
