name: '[CI] PR Reviewers 자동 지정'

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to users
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const reviewer1 = ['ZeroChoi2781', 'WynterKim'].filter(reviewer => reviewer !== prAuthor);
            const reviewer2 = ['MaxLee-dev', 'noaaaahh', 'ellen-lee-goorm'].filter(reviewer => reviewer !== prAuthor);

            const selectRandomReviewer = (reviewers) => reviewers[Math.floor(Math.random() * reviewers.length)];
            const reviewers = [selectRandomReviewer(reviewer1), selectRandomReviewer(reviewer2)];

            if (reviewers.length === 0) {
              console.log('No reviewers available.');
            } else {
              github.rest.pulls.requestReviewers({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                reviewers: reviewers
              });
            }