name: '[수동배포] (구)GDS 패키지'


on:
  workflow_dispatch:
        
jobs:
  deploy:
      runs-on: ubuntu-22.04
      steps:
          - name: checkout
            uses: actions/checkout@v4
            with:
              submodules: true

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 18
                registry-url: 'https://npm.pkg.github.com'

          - name: Get yarn cache directory path
            id: yarn-cache-dir-path
            run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

          - name: Set npm config
            run: npm config set @goorm-dev:registry=https://npm.pkg.github.com/ && npm config set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGE_TOKEN }}

          - name: Install Yarn
            run: |
              curl -L https://yarnpkg.com/install.sh | bash
              export PATH="$HOME/.local/bin:$PATH"

          - name: Install Dependencies
            run: yarn install:all
  
          - name: Build Packages
            run: yarn build:all
  
          - name: Publish new Package
            run: yarn run publish
            env:
                GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
                NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
  
          - name: Build Storybook
            run: yarn run build:storybook
  
          - name: Set env
            id: aws-var
            run: |
                echo "::set-output name=OUTPUT_PATH::storybook-static"
  
          - name: Set URL
            id: url
            run: |
                BASE_URL=${{ secrets.AWS_S3_BUCKET_NAME }}
                echo "::set-output name=PATH::${BASE_URL}"
  
          - name: Deploy S3
            run: |
                aws s3 cp ${{ steps.aws-var.outputs.OUTPUT_PATH }} s3://${{ steps.url.outputs.PATH }} --recursive
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
  
          #https://github.com/marketplace/actions/get-current-package-version
          #get version use package.json
          - name: Get current package version
            id: package-version
            uses: martinbeentjes/npm-get-version-action@v1.2.3
            with:
                path: packages/gds-components/
  
          - name: send slack success message
            run: |
              curl -X POST --data-urlencode "payload={\"username\": \"GDS-bot\", "attachments":[{"pretext":	'*@vapor-alarm* 구버전 GDS ${{ steps.package-version.outputs.current-version }}가 릴리즈 됐습니다 :older_person:',"color": '#CDCED6',"fields": [{ title: 'Change Log', value: '<https://gds.goorm.io/?path=/story/changelog--page|gds.goorm.io>', short: false }],},] }" "${{ secrets.SLACK_WEB_HOOK }}"